name: Actions workflow

on: [push]

jobs:
 run-github-actions:
   runs-on: ubuntu-latest
   steps:
    - name: Git Checkout
      uses: actions/checkout@v3
      with:
        ref: '278e7ba1fbd66a4f07cd644542f07e6f4b013566'
    - name: Workflow Script
      run: |
        cat .github/workflows/actions.yml
    - name: List files
      run: |
        pwd
        ls -a
    - name: Simple JS Action
      id: greet
      uses: actions/hello-world-javascript-action@v1
      with:
        who-to-greet: Anjith
    - name: Log Greeting Time
      run: echo "${{ steps.greet.outputs.time }}"
